### ISSUE TITLE
The Shared Link cannot pass verification

### ISSUE THREAD

**Issue by ealldy** [element-plus/element-plus-playground#135]
I try to paste the sharing link in the reproduction link input box.
But it cannot pass verification.
Hope it can be support, because the issue of element plus is one of the main uses of element plus playground.
![sharedLink](https://user-images.githubusercontent.com/41937421/151144263-1f4c6f11-7c44-433c-8732-9cb27cb8f2a8.png)
![errorLink](https://user-images.githubusercontent.com/41937421/151144275-ac501744-fb95-441b-87b6-870253137aa4.png)

chick here and have a try: https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

**Comment by sxzz** [comment]
Currently the issue helper does not support playground links. [A new issue helper](https://github.com/element-plus/element-plus-issue-helper) is already under development. 

You can fill in a link at will, when you jump to GitHub, then modify it to playground's link.
