### ISSUE TITLE
run locally and open brower with IP address error

### ISSUE THREAD

**Issue by hxgqh** [element-plus/element-plus-playground#148]
![image](https://user-images.githubusercontent.com/5571777/152970121-6c699196-fab3-4f71-b4b9-44d59ea875a7.png)

http://192.168.1.100:3000

**Comment by sxzz** [comment]
Playground uses `crypto.subtle.digest`. This [API](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest) requires HTTPS context or `localhost`.
