### ISSUE TITLE
360安全浏览器报错

### ISSUE THREAD

**Issue by tall-talker** [element-plus/element-plus-playground#190]
![image](https://user-images.githubusercontent.com/22855387/164894629-70e922e4-2c50-4a83-8d6d-c90db029d057.png)
运行环境：win10 64位/360安全浏览器13
![image](https://user-images.githubusercontent.com/22855387/164894761-081295a1-d568-4878-b19b-5b63c8700042.png)

**Comment by sxzz** [comment]
Please use latest Chrome/Edge/Firefox.

**Comment by sxzz** [comment]
Here is minimum required browser version.
https://caniuse.com/mdn-javascript_operators_await_top_level
