### ISSUE TITLE
el-table style in confusion

### ISSUE THREAD

**Issue by wenreq** [element-plus/element-plus-playground#196]
![1655451146869_ED6726FB-B0F1-4f03-BC4D-D50E97C34AEE](https://user-images.githubusercontent.com/31761376/174248880-80ec8a6e-07bd-4155-a029-5ad7d3c248d9.png)

**Comment by sxzz** [comment]
https://antfu.me/posts/why-reproductions-are-required-zh
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
