### ISSUE TITLE
safari run error

### ISSUE THREAD

**Issue by loosheng** [element-plus/element-plus-playground#215]
Env:
safari 16.1 (17614.2.9.1.13, 17614)
macOS 12.6.1 M1 Pro

Link:  Element  official  `Button`  [Example](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcm93IGNsYXNzPVwibWItNFwiPlxuICAgIDxlbC1idXR0b24+RGVmYXVsdDwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIj5QcmltYXJ5PC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwic3VjY2Vzc1wiPlN1Y2Nlc3M8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJpbmZvXCI+SW5mbzwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cIndhcm5pbmdcIj5XYXJuaW5nPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiZGFuZ2VyXCI+RGFuZ2VyPC9lbC1idXR0b24+XG4gIDwvZWwtcm93PlxuXG4gIDxlbC1yb3cgY2xhc3M9XCJtYi00XCI+XG4gICAgPGVsLWJ1dHRvbiBwbGFpbj5QbGFpbjwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBwbGFpbj5QcmltYXJ5PC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwic3VjY2Vzc1wiIHBsYWluPlN1Y2Nlc3M8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJpbmZvXCIgcGxhaW4+SW5mbzwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cIndhcm5pbmdcIiBwbGFpbj5XYXJuaW5nPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiZGFuZ2VyXCIgcGxhaW4+RGFuZ2VyPC9lbC1idXR0b24+XG4gIDwvZWwtcm93PlxuXG4gIDxlbC1yb3cgY2xhc3M9XCJtYi00XCI+XG4gICAgPGVsLWJ1dHRvbiByb3VuZD5Sb3VuZDwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiByb3VuZD5QcmltYXJ5PC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwic3VjY2Vzc1wiIHJvdW5kPlN1Y2Nlc3M8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJpbmZvXCIgcm91bmQ+SW5mbzwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cIndhcm5pbmdcIiByb3VuZD5XYXJuaW5nPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiZGFuZ2VyXCIgcm91bmQ+RGFuZ2VyPC9lbC1idXR0b24+XG4gIDwvZWwtcm93PlxuXG4gIDxlbC1yb3c+XG4gICAgPGVsLWJ1dHRvbiA6aWNvbj1cIlNlYXJjaFwiIGNpcmNsZSAvPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiA6aWNvbj1cIkVkaXRcIiBjaXJjbGUgLz5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJzdWNjZXNzXCIgOmljb249XCJDaGVja1wiIGNpcmNsZSAvPlxuICAgIDxlbC1idXR0b24gdHlwZT1cImluZm9cIiA6aWNvbj1cIk1lc3NhZ2VcIiBjaXJjbGUgLz5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJ3YXJuaW5nXCIgOmljb249XCJTdGFyXCIgY2lyY2xlIC8+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiZGFuZ2VyXCIgOmljb249XCJEZWxldGVcIiBjaXJjbGUgLz5cbiAgPC9lbC1yb3c+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHtcbiAgQ2hlY2ssXG4gIERlbGV0ZSxcbiAgRWRpdCxcbiAgTWVzc2FnZSxcbiAgU2VhcmNoLFxuICBTdGFyLFxufSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

Log:
<details>
<summary>Click to expand!</summary>

```shell
[Error] TypeError: __import_2__.setupElementPlus is not a function. (In '__import_2__.setupElementPlus()', '__import_2__.setupElementPlus' is undefined)
setup — c9c21a65-8500-4b48-9091-f35af5ec1a8a:18
callWithErrorHandling — 3271cbec-5271-4350-97f2-bf194ab99014:1662
setupStatefulComponent — 3271cbec-5271-4350-97f2-bf194ab99014:8646
setupComponent — 3271cbec-5271-4350-97f2-bf194ab99014:8601
mountComponent — 3271cbec-5271-4350-97f2-bf194ab99014:6933
processComponent — 3271cbec-5271-4350-97f2-bf194ab99014:6908
patch — 3271cbec-5271-4350-97f2-bf194ab99014:6512
render — 3271cbec-5271-4350-97f2-bf194ab99014:7668
mount — 3271cbec-5271-4350-97f2-bf194ab99014:5902
（匿名函数） — 3271cbec-5271-4350-97f2-bf194ab99014:10860
_mount — 848582f9-e57a-4b0a-997e-72225a512b6c:8
模块代码 — 848582f9-e57a-4b0a-997e-72225a512b6c:13
evaluate
moduleEvaluation
（匿名函数）
asyncFunctionResume
（匿名函数）
promiseReactionJobWithoutPromise
promiseReactionJob

	（匿名函数） (about:srcdoc:160)
	callWithErrorHandling (3271cbec-5271-4350-97f2-bf194ab99014:1662)
	handleError (3271cbec-5271-4350-97f2-bf194ab99014:1707)
	callWithErrorHandling (3271cbec-5271-4350-97f2-bf194ab99014:1665)
	setupStatefulComponent (3271cbec-5271-4350-97f2-bf194ab99014:8646)
	setupComponent (3271cbec-5271-4350-97f2-bf194ab99014:8601)
	mountComponent (3271cbec-5271-4350-97f2-bf194ab99014:6933)
	processComponent (3271cbec-5271-4350-97f2-bf194ab99014:6908)
	patch (3271cbec-5271-4350-97f2-bf194ab99014:6512)
	render (3271cbec-5271-4350-97f2-bf194ab99014:7668)
	mount (3271cbec-5271-4350-97f2-bf194ab99014:5902)
	（匿名函数） (3271cbec-5271-4350-97f2-bf194ab99014:10860)
	_mount (848582f9-e57a-4b0a-997e-72225a512b6c:8)
	模块代码 (848582f9-e57a-4b0a-997e-72225a512b6c:13)
	evaluate
	moduleEvaluation
	（匿名函数）
	asyncFunctionResume
	（匿名函数）
	promiseReactionJobWithoutPromise
	promiseReactionJob


[Error] TypeError: Module specifier, 'vue' does not start with "/", "./", or "../". Referenced from https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcm93IGNsYXNzPVwibWItNFwiPlxuICAgIDxlbC1idXR0b24+RGVmYXVsdDwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIj5QcmltYXJ5PC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwic3VjY2Vzc1wiPlN1Y2Nlc3M8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJpbmZvXCI+SW5mbzwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cIndhcm5pbmdcIj5XYXJuaW5nPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiZGFuZ2VyXCI+RGFuZ2VyPC9lbC1idXR0b24+XG4gIDwvZWwtcm93PlxuXG4gIDxlbC1yb3cgY2xhc3M9XCJtYi00XCI+XG4gICAgPGVsLWJ1dHRvbiBwbGFpbj5QbGFpbjwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBwbGFpbj5QcmltYXJ5PC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwic3VjY2Vzc1wiIHBsYWluPlN1Y2Nlc3M8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJpbmZvXCIgcGxhaW4+SW5mbzwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cIndhcm5pbmdcIiBwbGFpbj5XYXJuaW5nPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiZGFuZ2VyXCIgcGxhaW4+RGFuZ2VyPC9lbC1idXR0b24+XG4gIDwvZWwtcm93PlxuXG4gIDxlbC1yb3cgY2xhc3M9XCJtYi00XCI+XG4gICAgPGVsLWJ1dHRvbiByb3VuZD5Sb3VuZDwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiByb3VuZD5QcmltYXJ5PC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwic3VjY2Vzc1wiIHJvdW5kPlN1Y2Nlc3M8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJpbmZvXCIgcm91bmQ+SW5mbzwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cIndhcm5pbmdcIiByb3VuZD5XYXJuaW5nPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiZGFuZ2VyXCIgcm91bmQ+RGFuZ2VyPC9lbC1idXR0b24+XG4gIDwvZWwtcm93PlxuXG4gIDxlbC1yb3c+XG4gICAgPGVsLWJ1dHRvbiA6aWNvbj1cIlNlYXJjaFwiIGNpcmNsZSAvPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiA6aWNvbj1cIkVkaXRcIiBjaXJjbGUgLz5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJzdWNjZXNzXCIgOmljb249XCJDaGVja1wiIGNpcmNsZSAvPlxuICAgIDxlbC1idXR0b24gdHlwZT1cImluZm9cIiA6aWNvbj1cIk1lc3NhZ2VcIiBjaXJjbGUgLz5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJ3YXJuaW5nXCIgOmljb249XCJTdGFyXCIgY2lyY2xlIC8+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiZGFuZ2VyXCIgOmljb249XCJEZWxldGVcIiBjaXJjbGUgLz5cbiAgPC9lbC1yb3c+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHtcbiAgQ2hlY2ssXG4gIERlbGV0ZSxcbiAgRWRpdCxcbiAgTWVzc2FnZSxcbiAgU2VhcmNoLFxuICBTdGFyLFxufSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319 (x2)
```
</details>

![ele](https://user-images.githubusercontent.com/30114549/205003900-db57ad44-041b-498a-af68-d748dda6962d.gif)

**Comment by sxzz** [comment]
https://caniuse.com/import-maps

Try Safari >= 16.4 instead
