### ISSUE TITLE
icon图标增加一点小样式

### ISSUE THREAD

**Issue by Xxdoge** [element-plus/element-plus-playground#227]
可否给icon图标添加自定义hover颜色，类似于```<my-icon icon-name="Download" icon-color="#64B2C0" hover-color="#0C6E80"></my-icon>```这样的效果，这样当直接使用多个icon作为按钮时可以自定义每一个icon的样式

**Comment by sxzz** [comment]
非 playground 问题，请直接提交到 Element Plus 主仓库
https://github.com/element-plus/element-plus
