### ISSUE TITLE
element-plus-playground目前不支持增加html文件格式

### ISSUE THREAD

**Issue by yu0A** [element-plus/element-plus-playground#230]
目前，element-plus-playground只支持增加vue格式的页面（组件）。一般用户在ElementPlus上提Bug都会选择这个网站去复现问题，而和CDN相关的问题必须通过html来复现，因此这个工具的泛用性就大打折扣了。
希望可以增加增加html文件的功能，或者我改一版然后提个PR。

**Comment by sxzz** [comment]
目前并不考虑 CDN 相关问题，复杂需求请直接提交 git 仓库。
CDN-related issues are not currently considered, please submit complex requirements with git repository.
