### ISSUE TITLE
playground使用第三方插件报错

### ISSUE THREAD

**Issue by abczhangshasha** [element-plus/element-plus-playground#233]
![11](https://github.com/element-plus/element-plus-playground/assets/86042811/bdc676da-a4cc-4e06-addc-ed333dab7c4c)
![22](https://github.com/element-plus/element-plus-playground/assets/86042811/d55b132f-33af-4f85-9e81-77fd69d9c6b3)

**Comment by sxzz** [comment]
Please import CDN link of ESM format.
